# first step create workflow
name: githubaction2
on: 
  workflow_dispatch: 

jobs:
  say-hi:
    runs-on: ubuntu-latest
    
    steps:
      - name: say hello
        run: echo "run second workflow"
