# whenever change theh code in python linter will check
# linter checks if the synatax, indentation, format correct or not
#workflow

name: autolinter

on: 
  push: 
    paths:
      - "*.py"

jobs :
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout or clone the code
        # actions automate git clone command (use prebuilt action)
        uses: actions/checkout@v7 
        # this step install a linter tool
      
      - name: install linter
        run: pip install ruff
